/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, version 2.
 */

/** @file archipelago.h Archipelago multiworld randomizer integration. */

#ifndef ARCHIPELAGO_H
#define ARCHIPELAGO_H

#include <string>
#include <functional>
#include <thread>
#include <mutex>
#include <atomic>
#include <vector>
#include <set>
#include <algorithm>
#include <deque>
#include <map>

#include "town_type.h"
#include "tile_type.h"

struct Vehicle; ///< Forward declaration for AP_OnVehicleCreated

/** Connection states for the Archipelago client. */
enum class APState : uint8_t {
	DISCONNECTED,
	CONNECTING,
	CONNECTED,
	AUTHENTICATING,
	AUTHENTICATED,
	AP_ERROR,
};

/** A single item received from Archipelago. */
struct APItem {
	int64_t     item_id      = 0;
	std::string item_name;         ///< Resolved from slot_data item_id_to_name map
	int64_t     server_index = -1; ///< Position in AP server item list (0-based); -1 = unknown
};

/** A single mission generated by the APWorld. */
/** Named entity assigned to a mission at session start (town or industry on actual map). */
struct APNamedEntity {
	int32_t  id          = -1;       ///< TownID or IndustryID; -1 = not assigned
	std::string name;                ///< Display name substituted into mission description
	uint64_t cumulative  = 0;        ///< Accumulated progress (updated monthly)
	uint8_t  cargo_slot  = 0xFF;     ///< Industry cargo slot index (0xFF = not used)
	uint8_t  tae         = 0xFF;     ///< TownAcceptanceEffect (0xFF = not used)
	uint32_t tile        = UINT32_MAX; ///< Map tile (TileIndex) for viewport scroll; UINT32_MAX = unknown
	uint8_t   cargo_type = 0xFF; ///< Cargo type for cargomonitor (0xFF = invalid/not set)
};

struct APMission {
	std::string location;       ///< e.g. "Mission_Easy_001"
	std::string description;    ///< Human-readable goal text
	std::string type;           ///< "transport","earn £","have","service","build", etc.
	std::string difficulty;     ///< "easy","medium","hard","extreme"
	std::string cargo;          ///< May be empty
	std::string unit;           ///< "units","£","£/month","vehicles","trains","aircraft","road vehicles","towns","stations","passengers","purchase"
	int64_t     amount = 0;
	int64_t     current_value = 0; ///< Live progress – updated by CheckMissions() each tick
	bool        completed = false;
	/* "maintain" missions: counts consecutive months ALL stations have held the required rating */
	int32_t     maintain_months_ok = 0;
	bool        maintain_first_month_pending = true; ///< Absorb first timer fire after reset (prevents partial-month credit)
	/* Named entity missions: town or industry on the actual map */
	APNamedEntity named_entity;
};

/** A single cargo requirement for a ruin. */
struct APRuinCargoReq {
	uint8_t     cargo = 0xFF;     ///< Cargo type index
	std::string cargo_name;       ///< Display name (e.g. "Coal")
	int64_t     required  = 0;    ///< Amount needed
	int64_t     delivered = 0;    ///< Progress so far
};

/** An active ruin on the map, requiring cargo delivery to clear. */
struct APRuin {
	int              id = -1;             ///< Index into ruin_locations (0-based)
	std::string      location_name;       ///< "Ruin_001" etc.
	uint32_t         tile = UINT32_MAX;   ///< Map tile where object sits
	int              object_variant = 0;  ///< 0-5 (which ruin sprite)
	uint16_t         town_id = UINT16_MAX;///< Nearest town (for cargo monitor)
	std::string      town_name;           ///< Display name
	std::vector<APRuinCargoReq> cargo_reqs; ///< 2-3 cargo delivery requirements
	bool             completed = false;
};

/** A demigod boss definition received from APWorld slot_data. */
struct APDemigodDef {
	std::string location;        ///< "Demigod_001" — AP location name for check
	std::string name;            ///< "Demigod of Iron Rails" — company display name
	std::string president_name;  ///< "Lord Railsworth" — company president name
	std::string theme;           ///< "trains","road","aircraft","ships","freight","mixed"
	int64_t     tribute_cost = 0;///< Fixed cost in £ to defeat this demigod
};

/** Win condition difficulty preset ID (mirrors Python WinDifficulty). */
enum class APWinDifficulty : uint8_t {
	CASUAL    = 0,
	EASY      = 1,
	NORMAL    = 2,
	MEDIUM    = 3,
	HARD      = 4,
	VERY_HARD = 5,
	EXTREME   = 6,
	INSANE    = 7,
	NUTCASE   = 8,
	MADNESS   = 9,
	CUSTOM    = 10,
};

/** Current progress toward all six win targets. */
struct APWinProgress {
	int64_t company_value    = 0;
	int64_t town_population  = 0;
	int64_t vehicle_count    = 0;
	int64_t cargo_delivered  = 0;
	int64_t monthly_profit   = 0;
	int64_t missions         = 0;
};

/** Full configuration received from the AP server after authentication. */
struct APSlotData {
	std::string             game_version;
	int                     mission_count        = 0;
	int                     shop_slots           = 100; /* Fixed: all items always visible */
	std::string             starting_vehicle;
	std::string             starting_vehicle_type;
	std::vector<std::string> starting_vehicles;   ///< all starters (>1 for one_of_each)
	/* ── Win condition (multi-parameter) ──────────────────────────────── */
	APWinDifficulty         win_difficulty            = APWinDifficulty::NORMAL;
	int64_t                 win_target_company_value   = 8'000'000;
	int64_t                 win_target_town_population = 100'000;
	int64_t                 win_target_vehicle_count   = 30;
	int64_t                 win_target_cargo_delivered = 120'000;
	int64_t                 win_target_monthly_profit  = 100'000;
	int64_t                 win_target_missions        = 35;
	bool                    enable_traps         = true;
	int                     start_year           = 1950;

	/* World generation parameters */
	uint32_t                world_seed           = 0;
	uint8_t                 map_x                = 8;
	uint8_t                 map_y                = 8;
	uint8_t                 landscape            = 0;
	uint8_t                 land_generator       = 1;

	/* ── Game settings (Accounting) ─────────────────────────────────── */
	bool                    infinite_money       = false;
	bool                    inflation            = false;
	uint32_t                max_loan             = 300000;   ///< maximum initial loan in £
	bool                    infrastructure_maintenance = false;
	uint8_t                 vehicle_costs        = 1;        ///< 0=low,1=medium,2=high
	uint8_t                 construction_cost    = 1;        ///< 0=low,1=medium,2=high

	/* ── Game settings (Vehicles / Limitations) ─────────────────────── */
	uint16_t                max_trains           = 500;
	uint16_t                max_roadveh          = 500;
	uint16_t                max_aircraft         = 200;
	uint16_t                max_ships            = 300;
	uint16_t                max_train_length     = 7;        ///< in tiles — extended beyond vanilla 64
	uint16_t                station_spread       = 12;       ///< extended beyond vanilla 64
	bool                    road_stop_on_town_road       = true;
	bool                    road_stop_on_competitor_road = true;
	bool                    crossing_with_competitor     = true;

	/* ── Game settings (Disasters / Accidents) ──────────────────────── */
	bool                    disasters            = false;
	uint8_t                 plane_crashes        = 2;        ///< 0=none,1=reduced,2=normal
	uint8_t                 vehicle_breakdowns   = 1;        ///< 0=none,1=reduced,2=normal

	/* ── Game settings (Economy / Environment) ──────────────────────── */
	uint8_t                 economy_type         = 1;        ///< 0=original,1=smooth,2=frozen
	bool                    bribe                = true;
	bool                    exclusive_rights     = true;
	bool                    fund_buildings       = true;
	bool                    fund_roads           = true;
	bool                    give_money           = true;
	uint8_t                 town_growth_rate     = 2;        ///< 0=none,1=slow,2=normal,3=fast,4=very fast
	uint8_t                 found_town           = 0;        ///< 0=forbidden,1=allowed,2=custom layout
	uint16_t                town_cargo_scale     = 100;      ///< percent
	uint16_t                industry_cargo_scale = 100;      ///< percent
	uint8_t                 industry_density     = 4;        ///< 0=fund only, 1=minimal, 2=very low, 3=low, 4=normal, 5=high
	bool                    allow_town_roads     = true;

	/* ── Game settings (Vehicles / Routing) ─────────────────────────── */
	uint8_t                 road_side            = 1;        ///< 0=left,1=right

	/* ── Death Link ─────────────────────────────────────────────────── */
	bool                    death_link           = false;

	/* ── Difficulty / balance ───────────────────────────────────────── */
	int                     starting_cash_bonus  = 0;   ///< 0=none 1=50k 2=200k 3=500k 4=2M
	int                     starting_vehicle_count = 1; ///< used when starting_vehicle_type = custom
	int                     mission_difficulty   = 2;   ///< 0=veryeasy..4=veryhard (cosmetic only, stored for info)

	/* ── NewGRF options ─────────────────────────────────────────────── */
	bool                    enable_iron_horse    = false;

	/* ── Item Pool unlock options ───────────────────────────────────── */
	bool                    enable_rail_direction_unlocks = false;
	bool                    enable_road_direction_unlocks = false;
	bool                    enable_signal_unlocks         = false;
	bool                    enable_bridge_unlocks         = false;
	bool                    enable_tunnel_unlocks         = false;
	bool                    enable_airport_unlocks        = false;
	bool                    enable_tree_unlocks           = false;
	bool                    enable_terraform_unlocks      = false;
	bool                    enable_town_action_unlocks    = false;
	bool                    enable_wagon_unlocks          = false;

	/* ── Funny Stuff ────────────────────────────────────────────────── */
	bool                    community_vehicle_names = true; ///< Give built vehicles community names

	/* ── Colby Event ────────────────────────────────────────────────── */
	bool        colby_event      = false;   ///< Colby Event enabled by APWorld option
	int         colby_start_year = 0;       ///< in-game year the event triggers (start_year + 2)
	uint32_t    colby_town_seed  = 0;       ///< seed for deterministic town selection
	std::string colby_cargo      = "coal";  ///< climate-appropriate cargo (e.g. "coal", "rubber")

	/* ── Mission tier unlock requirements ──────────────────────────── */
	/// How many missions of the previous tier must be completed before the next tier unlocks.
	/// Keys: "medium", "hard", "extreme". Default 0 = always unlocked.
	std::map<std::string, int> tier_unlock_requirements;

	/** Maps item_id -> item_name, sent in slot_data by APWorld. */
	std::map<int64_t, std::string> item_id_to_name;

	/** Maps location_name -> price in £, sent in slot_data by APWorld. */
	std::map<std::string, int64_t> shop_prices;
	std::map<std::string, std::string> shop_item_names; ///< location_name → item display name

	/** Vehicle item names that should be locked at session start.
	 *  Only engines whose English name is in this set will be locked.
	 *  Engines NOT in this set (e.g. IH engines when enable_iron_horse=false)
	 *  are left available so the player can use them freely. */
	std::set<std::string> locked_vehicles;

	std::vector<APMission>  missions;

	/* ── Ruins ──────────────────────────────────────────────────────── */
	int                          ruin_pool_size    = 0;   ///< Total ruins over the game
	int                          max_active_ruins  = 6;   ///< Max simultaneous ruins on map
	int                          ruin_cargo_min    = 2;   ///< Min cargo types per ruin
	int                          ruin_cargo_max    = 4;   ///< Max cargo types per ruin
	std::vector<std::string>     ruin_locations;           ///< Ordered location names from APWorld

	/* ── Demigods (God of Wackens) ─────────────────────────────────── */
	bool                         demigod_enabled           = false;
	int                          demigod_count             = 0;
	int                          demigod_spawn_interval_min = 5;   ///< Min years between spawns
	int                          demigod_spawn_interval_max = 15;  ///< Max years between spawns
	std::vector<APDemigodDef>    demigods;

	/* ── Wrath of the God of Wackens ──────────────────────────────── */
	bool    wrath_enabled              = false;
	int     wrath_limit_houses         = 2;    ///< Houses destroyed/year before anger
	int     wrath_limit_roads          = 2;    ///< Town roads destroyed/year before anger
	int     wrath_limit_terrain        = 25;   ///< Terrain tiles modified/year before anger
	int     wrath_limit_trees          = 10;   ///< Trees removed/year before anger
};

/** Callbacks fired on the main thread via Tick(). */
struct APCallbacks {
	std::function<void()>                    on_connected;
	std::function<void(const std::string &)> on_disconnected;
	std::function<void(const APItem &)>      on_item_received;
	std::function<void(const std::string &)> on_print;
	std::function<void(const APSlotData &)>  on_slot_data;
	/** Fired when a Death Link bounce arrives from another player.
	 *  @param source  The slot name that sent the death. */
	std::function<void(const std::string &source)> on_death_received;
};

/** Archipelago WebSocket client. Networking runs in a background thread. */
class ArchipelagoClient {
public:
	ArchipelagoClient();
	~ArchipelagoClient();

	void Connect(const std::string &host, uint16_t port,
	             const std::string &slot, const std::string &password,
	             const std::string &game = "OpenTTD-Exp",
	             bool use_ssl = false);
	void Disconnect();

	/** Send a location check by numeric ID. */
	void SendCheck(int64_t location_id);

	/** Send a location check by name (looks up ID from slot data). */
	void SendCheckByName(const std::string &location_name);

	/** Send victory / goal-complete status. */
	void SendGoal();
	void SendScoutsForShop(); ///< Scout all shop locations to get player/game labels

	/** Send a chat/command message to the AP server (e.g. "!hint item"). */
	void SendSay(const std::string &text);

	/** Send a Death Link bounce packet to the server.
	 *  @param cause Short human-readable description, e.g. "Train crash". */
	void SendDeath(const std::string &cause);

	/** Returns the "player (game)" hint label for a shop location, or "" if not yet resolved. */
	std::string GetLocationHint(const std::string &location_name) const {
		auto id_it = location_ids.find(location_name);
		if (id_it == location_ids.end()) return "";
		auto hint_it = location_id_to_hint.find(id_it->second);
		if (hint_it == location_id_to_hint.end()) return "";
		return hint_it->second;
	}

	/** Dispatch queued callbacks on the main thread. Call every game tick. */
	void Tick();

	APState     GetState()     const { return state.load(); }
	std::string GetLastError() const { std::lock_guard<std::mutex> lg(slot_mutex); return last_error; }

	APSlotData GetSlotData() const {
		std::lock_guard<std::mutex> lg(slot_mutex);
		return slot_data;
	}
	bool HasSlotData() const { return has_slot_data.load(); }

	/** Returns all player alias names from the multiworld (deduplicated, sorted). */
	std::vector<std::string> GetPlayerNames() const {
		std::lock_guard<std::mutex> lg(slot_mutex);
		std::vector<std::string> result;
		std::set<std::string>    seen;
		for (auto &[id, name] : player_id_to_name) {
			if (!name.empty() && seen.insert(name).second)
				result.push_back(name);
		}
		std::sort(result.begin(), result.end());
		return result;
	}

	APCallbacks callbacks;

private:
	std::atomic<APState> state{ APState::DISCONNECTED };
	std::string last_error;

	std::string host, slot_name, password, game_name;
	uint16_t    port = 0;
	bool        ws_deflate{ false };   ///< true if server accepted permessage-deflate
	bool        use_ssl{ false };      ///< true → TLS/WSS via Schannel (Windows)

	double      last_death_link_time{ 0.0 }; ///< Timestamp of last DeathLink sent/received (for dedup)

	mutable std::mutex slot_mutex;
	APSlotData         slot_data;
	std::atomic<bool>  has_slot_data{ false };

	/* Location name -> ID (filled from slot_data) */
	std::map<std::string, int64_t> location_ids;
	std::map<int64_t, std::string> location_id_to_name; ///< Reverse of location_ids
	std::map<int64_t, std::string> player_id_to_name;   ///< Slot number → player alias
	std::map<int64_t, std::string> player_id_to_game;   ///< Slot number → game name
	std::map<int64_t, std::string> location_id_to_hint; ///< location_id → "player (game)" label

	std::thread        worker_thread;
	std::atomic<bool>  stop_requested{ false };

	struct InboundEvent {
		enum Type : uint8_t { CONNECTED, DISCONNECTED, ITEM, PRINT, SLOT_DATA, DEATH_RECEIVED } type;
		std::string text;
		APItem      item;
		APSlotData  slot;
	};
	std::mutex               inbound_mutex;
	std::deque<InboundEvent> inbound_queue;

	struct OutboundMsg { std::string json; };
	std::mutex               outbound_mutex;
	std::deque<OutboundMsg>  outbound_queue;

	void        WorkerThread();
	bool        DoWebSocketHandshake(int sock, const std::string &h, uint16_t p);
	bool        SendWsText(int sock, const std::string &text);
	bool        RecvWsFrame(int sock, std::string &out_text, bool &out_closed);
	void        ProcessAPMessage(const std::string &json_text);
	void        PushEvent(InboundEvent ev);
	std::string PopOutbound();
	void        SetLastErrorInternal(const std::string &err) { std::lock_guard<std::mutex> lg(slot_mutex); last_error = err; }

#ifdef _WIN32
	void InitWinsock();
#endif
};

extern ArchipelagoClient *_ap_client;
void InitArchipelago();
void UninitArchipelago();

/**
 * Returns true when an Archipelago session is active (authenticated).
 * Called from engine.cpp to block the vanilla date-based vehicle introduction.
 */
bool AP_IsActive();

/** Forward a text/command string to the AP server (Say packet). */
void AP_SendSay(const std::string &text);

/** Register the "ap" console command. Call once at startup. */
void AP_RegisterConsoleCommands();

/** Open the Archipelago Guide window. */
void ShowArchipelagoGuideWindow();

/** Open the Archipelago Vehicle Index window. */
void ShowArchipelagoIndexWindow();

/** Returns true if the given EngineID has been unlocked via Archipelago items. */
bool AP_IsEngineUnlocked(uint32_t engine_id);

/** Returns true if Colby Event is active and not yet completed. */
bool AP_IsColbyActive();
bool AP_IsColbyConfigured();

/** Mission completion counters. */
int AP_GetTierCompleted(const std::string &difficulty);
int AP_GetTotalMissionsCompleted();
int64_t AP_GetItemsReceivedCount();
APWinProgress AP_GetWinProgress();

/** Shop slot locking: returns true if the given 0-based sorted slot is unlocked. */
bool AP_IsShopSlotUnlocked(int slot_index);
int  AP_GetShopSlotRequiredMissions(int slot_index);

/** Called by vehicle build commands — assigns a community name when AP is active. */
void AP_OnVehicleCreated(Vehicle *v);

/** Tier unlock helpers. */
int  AP_GetTierThreshold(const std::string &difficulty);
bool AP_IsTierUnlocked(const std::string &difficulty);

/**
 * Returns true if the given track direction is locked for the given rail type.
 * Called from rail_cmd.cpp CmdRailTrackHelper to block locked track builds.
 * @param railtype  The RailType value (0=Normal, 1=Electric, 2=Mono, 3=Maglev)
 * @param track     The Track value (0=TRACK_X .. 5=TRACK_RIGHT)
 */
bool AP_IsTrackDirLocked(uint8_t railtype, uint8_t track);

/** Get the full locked-directions bitmask for a rail type (bits 0-5 = TRACK_X..TRACK_RIGHT). */
uint8_t AP_GetLockedTrackDirs(uint8_t railtype);

/** Back-compat shim — deprecated, always returns false. Use AP_IsTrackDirLocked. */
bool AP_IsRailDirectionLocked(uint8_t track);

/** Infrastructure lock checks — called from command intercepts. */
bool AP_IsRoadDirLocked(uint8_t axis);        ///< axis: 0=X (NE-SW), 1=Y (NW-SE)
bool AP_IsSignalLocked(uint8_t sigtype);       ///< sigtype: 0-5 (SignalType enum)
bool AP_IsBridgeLocked(uint8_t bridge_type);   ///< bridge_type: 0-12
bool AP_IsBridgeLocked();                      ///< true if ANY bridge type is locked
bool AP_IsTunnelLocked();
bool AP_IsAirportLocked(uint8_t airport_type); ///< airport_type: 0-8, AT_SMALL always returns false
bool AP_IsTreeLocked(uint8_t tree_type);       ///< tree_type: raw TreeType value
bool AP_IsTerraformRaiseLocked();
bool AP_IsTerraformLowerLocked();
bool AP_IsTownActionLocked(uint8_t action_idx); ///< action_idx: 0-7 (TownAction enum)
bool AP_IsTownActionLocked();                   ///< true if ANY town action is locked

/** Save/load getters and setters for infrastructure locks. */
uint8_t  AP_GetLockedRoadDirs();
void     AP_SetLockedRoadDirs(uint8_t mask);
uint8_t  AP_GetLockedSignals();
void     AP_SetLockedSignals(uint8_t mask);
uint16_t AP_GetLockedBridges();
void     AP_SetLockedBridges(uint16_t mask);
bool     AP_GetLockedTunnels();
void     AP_SetLockedTunnels(bool v);
uint16_t AP_GetLockedAirports();
void     AP_SetLockedAirports(uint16_t mask);
uint16_t AP_GetLockedTrees();
void     AP_SetLockedTrees(uint16_t mask);
uint8_t  AP_GetLockedTerraform();
void     AP_SetLockedTerraform(uint8_t mask);
uint8_t  AP_GetLockedTownActions();
void     AP_SetLockedTownActions(uint8_t mask);

/** Colby Event status snapshot for the GUI. */
struct ColbyStatus {
	bool        enabled;
	bool        done;
	int         step;
	int64_t     delivered;
	int64_t     step_amount;
	bool        escaped;
	bool        popup_shown;
	int         escape_ticks;
	std::string town_name;
	TownID      town_id         = (TownID)UINT16_MAX;
	TileIndex   source_tile     = INVALID_TILE;
	std::string source_name;   ///< station name for pickup
	std::string cargo_name;    ///< "packages"
};
ColbyStatus AP_GetColbyStatus();

/** Demigod system status snapshot for the GUI. */
struct DemigodStatus {
	bool        enabled;
	bool        active;          ///< A demigod company is currently alive
	int         defeated_count;
	int         total_count;
	int         active_idx;      ///< -1 = none
	std::string active_name;
	std::string active_theme;
	int64_t     tribute_cost;
	int         active_company;  ///< CompanyID raw value, -1 = invalid
	int         next_spawn_year; ///< 0 = N/A
};
DemigodStatus AP_GetDemigodStatus();
void AP_DemigodDefeat();   ///< Called from GUI on tribute click
bool AP_IsDemigodEnabled();

/* ── Wrath of the God of Wackens ──────────────────────────────── */
void AP_WrathTrackHouse();      ///< Called from town_cmd.cpp on house demolition
void AP_WrathTrackRoad();       ///< Called from road_cmd.cpp on town road removal
void AP_WrathTrackTerrain();    ///< Called from terraform_cmd.cpp on terraform execute
void AP_WrathTrackTree();       ///< Called from tree_cmd.cpp on tree clearing

struct WrathStatus {
	bool enabled;
	int  anger_level;
	int  houses_this_year, roads_this_year, terrain_this_year, trees_this_year;
	int  limit_houses, limit_roads, limit_terrain, limit_trees;
};
WrathStatus AP_GetWrathStatus();
bool AP_IsWrathEnabled();

void AP_GetWrathState(int *anger, int *houses, int *roads, int *terrain, int *trees, int *last_eval_year);
void AP_SetWrathState(int anger, int houses, int roads, int terrain, int trees, int last_eval_year);

/* Fast-forward speed (controlled by Speed Boost items).
 * Starts at 100 (normal), each Speed Boost item adds 10, capped at 300. */
int  AP_GetFfSpeed();
void AP_SetFfSpeed(int v);

/* News filter: 0=Off, 1=Self only, 2=All (self + others). */
extern int _ap_news_filter;

/* ── Ruin interaction API ─────────────────────────────────────────── */
/* Cargo acceptance — called from object_cmd.cpp (declared locally there
 * to avoid cargo_type.h dependency in this header). */

/** Snapshot of a single ruin for GUI display. */
struct APRuinView {
	int         id;             ///< Ruin index (0-based)
	std::string location_name;  ///< "Ruin_001"
	uint32_t    tile;           ///< Map tile
	std::string town_name;      ///< Nearest town display name
	bool        completed;
	struct CargoLine {
		std::string name;       ///< "Coal", "Iron Ore", etc.
		int64_t     required;
		int64_t     delivered;
	};
	std::vector<CargoLine> cargo;
};

/** Return ruin view for the ruin at the given tile, or nullptr-equivalent (empty optional). */
bool AP_GetRuinViewByTile(uint32_t tile_index, APRuinView &out);

/** Check if tile is an active (non-completed) ruin. */
bool AP_IsRuinTile(uint32_t tile_index);

/** Get all ruins (active + completed) for listing in the industry directory. */
std::vector<APRuinView> AP_GetAllRuinViews();

/* =========================================================================
 * LOCAL TASK SYSTEM
 *
 * Tasks are purely local (never sent to AP server).
 * Up to 5 active at once; complete/expire to make room for new ones.
 * "Mission Check" reward counts toward the shop-unlock counter.
 * ========================================================================= */

enum class APTaskRewardType : uint8_t {
    CASH,           ///< Give company money on completion
    MISSION_CHECK,  ///< Count as a completed mission for shop-unlock counter
};

struct APTask {
    int         id              = 0;
    std::string type;                    ///< "cargo_from_industry", "passengers_to_town"
    std::string description;
    int64_t     amount          = 0;     ///< Target quantity
    int64_t     current_value   = 0;     ///< Live progress (updated monthly)
    bool        completed       = false;
    bool        expired         = false;
    bool        monitor_seeded  = false; ///< True once the cargo monitor has been drained on creation
    int32_t     deadline_year   = 0;
    uint8_t     deadline_month  = 1;
    int32_t     removal_year    = 0;     ///< Year when this task is removed from the list (0 = not scheduled)
    APTaskRewardType reward_type = APTaskRewardType::CASH;
    int64_t     reward_cash     = 0;
    int32_t     entity_id       = -1;    ///< IndustryID (cargo) or TownID (passengers)
    uint8_t     cargo           = 0xFF;  ///< CargoType; 0xFF = not used
    uint32_t    entity_tile     = UINT32_MAX;
    std::string entity_name;             ///< Display name (shown in TC_WHITE in GUI)
    std::string difficulty;              ///< "easy", "medium", "hard"
};

/** Returns a snapshot copy of the active task list (for GUI rendering). */
std::vector<APTask> AP_GetTaskSnapshot();

/** Returns how many task Mission-Check rewards have been collected this session. */
int AP_GetTaskChecksCompleted();

/** Generate/replenish tasks up to the active cap from the current map. */
void AP_GenerateTasks();

/** Saveload helpers for task state. */
std::string AP_GetTasksStr();
void        AP_SetTasksStr(const std::string &s);
int         AP_GetTaskChecksCompletedSaved();
void        AP_SetTaskChecksCompleted(int v);

/** Saveload helpers for vehicle name pool persistence. */
std::string AP_GetNamePoolStr();
void        AP_SetNamePoolStr(const std::string &s);

/** Saveload helpers for demigod state. */
void AP_GetDemigodState(std::string *defeated, int *active_idx, int *company,
                        int *next_year, bool *veh_saved, bool *sv_train,
                        bool *sv_road, bool *sv_air, bool *sv_ship);
void AP_SetDemigodState(const std::string &defeated, int active_idx, int company,
                        int next_year, bool veh_saved, bool sv_train,
                        bool sv_road, bool sv_air, bool sv_ship);

#endif /* ARCHIPELAGO_H */
