/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, version 2.
 */

/** @file archipelago.h Archipelago multiworld randomizer integration. */

#ifndef ARCHIPELAGO_H
#define ARCHIPELAGO_H

#include <string>
#include <functional>
#include <thread>
#include <mutex>
#include <atomic>
#include <vector>
#include <deque>
#include <map>

/** Connection states for the Archipelago client. */
enum class APState : uint8_t {
	DISCONNECTED,
	CONNECTING,
	CONNECTED,
	AUTHENTICATING,
	AUTHENTICATED,
	AP_ERROR,
};

/** A single item received from Archipelago. */
struct APItem {
	int64_t     item_id   = 0;
	std::string item_name;       ///< Resolved from slot_data item_id_to_name map
};

/** A single mission generated by the APWorld. */
struct APMission {
	std::string location;       ///< e.g. "Mission_Easy_001"
	std::string description;    ///< Human-readable goal text
	std::string type;           ///< "transport","earn £","have","service","build", etc.
	std::string difficulty;     ///< "easy","medium","hard","extreme"
	std::string cargo;          ///< May be empty
	std::string unit;           ///< "units","£","£/month","vehicles","trains","aircraft","road vehicles","towns","stations","passengers","purchase"
	int64_t     amount = 0;
	int64_t     current_value = 0; ///< Live progress – updated by CheckMissions() each tick
	bool        completed = false;
	/* "maintain" missions: counts consecutive months ALL stations have held the required rating */
	int32_t     maintain_months_ok = 0;
};

/** Win condition type. */
enum class APWinCondition : uint8_t {
	COMPANY_VALUE,
	TOWN_POPULATION,
	VEHICLE_COUNT,
	CARGO_DELIVERED,
	MONTHLY_PROFIT,
};

/** Full configuration received from the AP server after authentication. */
struct APSlotData {
	std::string             game_version;
	int                     mission_count        = 0;
	int                     shop_slots           = 5;
	int                     shop_refresh_days    = 90;
	std::string             starting_vehicle;
	std::string             starting_vehicle_type;
	APWinCondition          win_condition        = APWinCondition::COMPANY_VALUE;
	int64_t                 win_condition_value  = 50000000;
	bool                    enable_traps         = true;
	int                     start_year           = 1950;

	/* World generation parameters */
	uint32_t                world_seed           = 0;
	uint8_t                 map_x                = 8;
	uint8_t                 map_y                = 8;
	uint8_t                 landscape            = 0;
	uint8_t                 land_generator       = 1;

	/* ── Game settings (Accounting) ─────────────────────────────────── */
	bool                    infinite_money       = false;
	bool                    inflation            = false;
	uint32_t                max_loan             = 300000;   ///< maximum initial loan in £
	bool                    infrastructure_maintenance = false;
	uint8_t                 vehicle_costs        = 1;        ///< 0=low,1=medium,2=high
	uint8_t                 construction_cost    = 1;        ///< 0=low,1=medium,2=high

	/* ── Game settings (Vehicles / Limitations) ─────────────────────── */
	uint16_t                max_trains           = 500;
	uint16_t                max_roadveh          = 500;
	uint16_t                max_aircraft         = 200;
	uint16_t                max_ships            = 300;
	uint16_t                max_train_length     = 7;        ///< in tiles — extended beyond vanilla 64
	uint16_t                station_spread       = 12;       ///< extended beyond vanilla 64
	bool                    road_stop_on_town_road       = true;
	bool                    road_stop_on_competitor_road = true;
	bool                    crossing_with_competitor     = true;

	/* ── Game settings (Disasters / Accidents) ──────────────────────── */
	bool                    disasters            = false;
	uint8_t                 plane_crashes        = 2;        ///< 0=none,1=reduced,2=normal
	uint8_t                 vehicle_breakdowns   = 1;        ///< 0=none,1=reduced,2=normal

	/* ── Game settings (Economy / Environment) ──────────────────────── */
	uint8_t                 economy_type         = 1;        ///< 0=original,1=smooth,2=frozen
	bool                    bribe                = true;
	bool                    exclusive_rights     = true;
	bool                    fund_buildings       = true;
	bool                    fund_roads           = true;
	bool                    give_money           = true;
	uint8_t                 town_growth_rate     = 2;        ///< 0=none,1=slow,2=normal,3=fast,4=very fast
	uint8_t                 found_town           = 0;        ///< 0=forbidden,1=allowed,2=custom layout
	uint16_t                town_cargo_scale     = 100;      ///< percent
	uint16_t                industry_cargo_scale = 100;      ///< percent
	uint8_t                 industry_density     = 4;        ///< 0=fund only, 1=minimal, 2=very low, 3=low, 4=normal, 5=high
	bool                    allow_town_roads     = true;

	/* ── Game settings (Vehicles / Routing) ─────────────────────────── */
	uint8_t                 road_side            = 1;        ///< 0=left,1=right

	/* ── Death Link ─────────────────────────────────────────────────── */
	bool                    death_link           = false;

	/** Maps item_id -> item_name, sent in slot_data by APWorld. */
	std::map<int64_t, std::string> item_id_to_name;

	/** Maps location_name -> price in £, sent in slot_data by APWorld. */
	std::map<std::string, int64_t> shop_prices;

	std::vector<APMission>  missions;
};

/** Callbacks fired on the main thread via Tick(). */
struct APCallbacks {
	std::function<void()>                    on_connected;
	std::function<void(const std::string &)> on_disconnected;
	std::function<void(const APItem &)>      on_item_received;
	std::function<void(const std::string &)> on_print;
	std::function<void(const APSlotData &)>  on_slot_data;
	/** Fired when a Death Link bounce arrives from another player.
	 *  @param source  The slot name that sent the death. */
	std::function<void(const std::string &source)> on_death_received;
};

/** Archipelago WebSocket client. Networking runs in a background thread. */
class ArchipelagoClient {
public:
	ArchipelagoClient();
	~ArchipelagoClient();

	void Connect(const std::string &host, uint16_t port,
	             const std::string &slot, const std::string &password,
	             const std::string &game = "OpenTTD",
	             bool use_ssl = false);
	void Disconnect();

	/** Send a location check by numeric ID. */
	void SendCheck(int64_t location_id);

	/** Send a location check by name (looks up ID from slot data). */
	void SendCheckByName(const std::string &location_name);

	/** Send victory / goal-complete status. */
	void SendGoal();
	void SendScoutsForShop(); ///< Scout all shop locations to get player/game labels

	/** Send a Death Link bounce packet to the server.
	 *  @param cause Short human-readable description, e.g. "Train crash". */
	void SendDeath(const std::string &cause);

	/** Returns the "player (game)" hint label for a shop location, or "" if not yet resolved. */
	std::string GetLocationHint(const std::string &location_name) const {
		auto id_it = location_ids.find(location_name);
		if (id_it == location_ids.end()) return "";
		auto hint_it = location_id_to_hint.find(id_it->second);
		if (hint_it == location_id_to_hint.end()) return "";
		return hint_it->second;
	}

	/** Dispatch queued callbacks on the main thread. Call every game tick. */
	void Tick();

	APState     GetState()     const { return state.load(); }
	std::string GetLastError() const { return last_error; }

	APSlotData GetSlotData() const {
		std::lock_guard<std::mutex> lg(slot_mutex);
		return slot_data;
	}
	bool HasSlotData() const { return has_slot_data.load(); }

	APCallbacks callbacks;

private:
	std::atomic<APState> state{ APState::DISCONNECTED };
	std::string last_error;

	std::string host, slot_name, password, game_name;
	uint16_t    port = 0;
	bool        ws_deflate{ false };   ///< true if server accepted permessage-deflate
	bool        use_ssl{ false };      ///< true → TLS/WSS via Schannel (Windows)

	mutable std::mutex slot_mutex;
	APSlotData         slot_data;
	std::atomic<bool>  has_slot_data{ false };

	/* Location name -> ID (filled from slot_data) */
	std::map<std::string, int64_t> location_ids;
	std::map<int64_t, std::string> location_id_to_name; ///< Reverse of location_ids
	std::map<int64_t, std::string> player_id_to_name;   ///< Slot number → player alias
	std::map<int64_t, std::string> player_id_to_game;   ///< Slot number → game name
	std::map<int64_t, std::string> location_id_to_hint; ///< location_id → "player (game)" label

	std::thread        worker_thread;
	std::atomic<bool>  stop_requested{ false };

	struct InboundEvent {
		enum Type : uint8_t { CONNECTED, DISCONNECTED, ITEM, PRINT, SLOT_DATA, DEATH_RECEIVED } type;
		std::string text;
		APItem      item;
		APSlotData  slot;
	};
	std::mutex               inbound_mutex;
	std::deque<InboundEvent> inbound_queue;

	struct OutboundMsg { std::string json; };
	std::mutex               outbound_mutex;
	std::deque<OutboundMsg>  outbound_queue;

	void        WorkerThread();
	bool        DoWebSocketHandshake(int sock, const std::string &h, uint16_t p);
	bool        SendWsText(int sock, const std::string &text);
	bool        RecvWsFrame(int sock, std::string &out_text, bool &out_closed);
	void        ProcessAPMessage(const std::string &json_text);
	void        PushEvent(InboundEvent ev);
	std::string PopOutbound();

#ifdef _WIN32
	void InitWinsock();
#endif
};

extern ArchipelagoClient *_ap_client;
void InitArchipelago();
void UninitArchipelago();

/**
 * Returns true when an Archipelago session is active (authenticated).
 * Called from engine.cpp to block the vanilla date-based vehicle introduction.
 */
bool AP_IsActive();

#endif /* ARCHIPELAGO_H */
